-- POI (point of interest) guide layouts.
--
-- First parameter is X, the second is Y, origin is lower left.
-- Grid is 6 inches.
-- I overlayed all map cards and entered the coordinates for all
-- current maps. Might be worth a double check, it didn't align
-- perfectly with the POI overlay, which is missing many of the new ones.
function getPoiLayout6x3()
  return {
    {1, 2},
    {1, 3},
    {1, 4},
    {2.5, 2},
    {3, 1.5},
    {3, 2},
    {3, 3},
    {3, 4.5},
    {3, 5},
    {4, 1},
    {4, 2},
    {4, 4},
    {4.5, 3},
    {5, 4},
    {6, 1},
    {6, 2},
    {6, 3},
    {6, 4},
    {6, 5},
    {7, 2},
    {7.5, 3},
    {8, 2},
    {8, 4},
    {8, 5},
    {9, 1},
    {9, 1.5},
    {9, 3},
    {9, 4},
    {9, 4.5},
    {9.5, 4},
    {11, 2},
    {11, 3},
    {11, 4},
  }
end

-- Half-length 3x3 battlefield: X and Y, same as above
function getPoiLayout3x3()
  return {
    {1, 2},
    {1, 3},
    {1, 4},
    {3, 1},
    {3, 3},
    {3, 5},
    {5, 2},
    {5, 3},
    {5, 4},
  }
end
